Import( "env" )

from pathlib import Path

PROJECT_DIR = Path( env["PROJECT_DIR"] )
ENV_CANDIDATES = [
    PROJECT_DIR / ".env",
    PROJECT_DIR.parent / ".env",
]
HEADER_PATH = PROJECT_DIR / "include" / "env_build.h"

KEY_MAP = {
    "WIFI_SSID": "WIFI_SSID_ENV",
    "WIFI_PASS": "WIFI_PASS_ENV",
    "PC_PING_URL": "PC_PING_URL_ENV",
    "API_TOKEN": "API_TOKEN_ENV",
    "ESP32_STATIC_IP": "ESP32_STATIC_IP_ENV",
    "ESP32_GATEWAY": "ESP32_GATEWAY_ENV",
    "ESP32_SUBNET": "ESP32_SUBNET_ENV",
    "ESP32_DNS": "ESP32_DNS_ENV",
}


def parse_env_line( line ):
    stripped = line.strip()
    if not stripped or stripped.startswith( "#" ):
        return None, None
    if "=" not in stripped:
        return None, None

    key, value = stripped.split( "=", 1 )
    key = key.strip()
    value = value.strip()

    if len( value ) >= 2 and value[0] == value[-1] and value[0] in ["\"", "'"]:
        value = value[1:-1]

    return key, value


def c_string_define_value( text ):
    escaped = text.replace( "\\", "\\\\" ).replace( '"', '\\"' )
    return '"' + escaped + '"'


env_file = None
for candidate in ENV_CANDIDATES:
    if candidate.exists():
        env_file = candidate
        break

header_lines = [
    "// Auto-generated by scripts/load_env.py",
    "#pragma once",
    "",
]

if env_file is not None:
    content = env_file.read_text( encoding="utf-8" ).splitlines()
    loaded = 0

    for raw in content:
        key, value = parse_env_line( raw )
        if not key or key not in KEY_MAP:
            continue

        macro = KEY_MAP[key]
        header_lines.append( f"#define {macro} {c_string_define_value( value )}" )
        loaded += 1

    print( f"[load_env] Loaded {loaded} value(s) from {env_file}" )
else:
    paths = ", ".join( str( p ) for p in ENV_CANDIDATES )
    print( f"[load_env] No .env found in: {paths}. Using defaults from source." )

HEADER_PATH.parent.mkdir( parents=True, exist_ok=True )
HEADER_PATH.write_text( "\n".join( header_lines ) + "\n", encoding="utf-8" )
print( f"[load_env] Wrote generated header: {HEADER_PATH}" )
