; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:test_parts]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  DFRobotDFPlayerMini
src_filter =
  +<test-parts.cpp>
  -<main.cpp>

[env:main_run]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  DFRobotDFPlayerMini
monitor_speed = 115200
extra_scripts =
  pre:scripts/load_env.py
build_src_filter =
  +<main.cpp>
  -<test-parts.cpp>
